rm(list = ls())


ncp0 <- rt(10000, 10, 0)
ncp0.5 <- rt(10000, 10, 0.5)
ncp1 <- rt(10000, 10, 1)
ncp1.5 <- rt(10000, 10, 1.5)
ncp2 <- rt(10000, 10, 2)
ncp3 <- rt(10000, 10, 3)
ncp5 <- rt(10000, 10, 5)

ncp0 <- dt(10000, 10, 0)
ncp0.5 <- dt(10000, 10, 0.5)
ncp1 <- dt(10000, 10, 1)
ncp1.5 <- dt(10000, 10, 1.5)
ncp2 <- dt(10000, 10, 2)
ncp3 <- dt(10000, 10, 3)
ncp5 <- dt(10000, 10, 5)

ncp0 <- pt(1:10000, 10, 0)
ncp0.5 <- pt(1:10000, 10, 0.5)
ncp1 <- pt(1:10000, 10, 1)
ncp1.5 <- pt(1:10000, 10, 1.5)
ncp2 <- pt(1:10000, 10, 2)
ncp3 <- pt(1:10000, 10, 3)
ncp5 <- pt(1:10000, 10, 5)

par(mfrow = c(1,1))
plot(density(ncp0), main = "noncentral parameters with same df", xlim = c(-5,15), ylim = c(0,0.4), xlab = "")
par(new = T)
plot(density(ncp0.5), main = "noncentral parameters with same df", xlim = c(-5,15), ylim = c(0,0.4), xlab = "", col = "blue")
par(new = T)
plot(density(ncp1), main = "noncentral parameters with same df", xlim = c(-5,15), ylim = c(0,0.4), xlab = "", col = "skyblue")
par(new = T)
plot(density(ncp1.5), main = "noncentral parameters with same df", xlim = c(-5,15), ylim = c(0,0.4), xlab = "", col = "darkgreen")
par(new = T)
plot(density(ncp2), main = "noncentral parameters with same df", xlim = c(-5,15), ylim = c(0,0.4), xlab = "", col = "orange")
par(new = T)
plot(density(ncp3), main = "noncentral parameters with same df", xlim = c(-5,15), ylim = c(0,0.4), xlab = "", col = "purple")
par(new = T)
plot(density(ncp5), main = "noncentral parameters with same df", xlim = c(-5,15), ylim = c(0,0.4), xlab = "", col = "red")

par(mfrow = c(1,1))
plot(ecdf(ncp0), main = "noncentral parameters with same df", xlim = c(-5, 15), ylim = c(0, 1), xlab = "")
par(new = T)
plot(ecdf(ncp0.5), main = "noncentral parameters with same df", xlim = c(-5, 15), ylim = c(0, 1), xlab = "", col = "blue")
par(new = T)
plot(ecdf(ncp1), main = "noncentral parameters with same df", xlim = c(-5, 15), ylim = c(0, 1), xlab = "", col = "skyblue")
par(new = T)
plot(ecdf(ncp1.5), main = "noncentral parameters with same df", xlim = c(-5, 15), ylim = c(0, 1), xlab = "", col = "darkgreen")
par(new = T)
plot(ecdf(ncp2), main = "noncentral parameters with same df", xlim = c(-5, 15), ylim = c(0, 1), xlab = "", col = "orange")
par(new = T)
plot(ecdf(ncp3), main = "noncentral parameters with same df", xlim = c(-5, 15), ylim = c(0, 1), xlab = "", col = "purple")
par(new = T)
plot(ecdf(ncp5), main = "noncentral parameters with same df", xlim = c(-5, 15), ylim = c(0, 1), xlab = "", col = "red")

df5 <- rt(10000, 5, 5)
df10 <- rt(10000, 10, 5)
df20 <- rt(10000, 20, 5)
df30 <- rt(10000, 30, 5)
df50 <- rt(10000, 50, 5)
df100 <- rt(10000, 100, 5)

par(mfrow = c(1,1))
plot(density(df5), main = "df's with same noncentral parmeter", xlim = c(0,12), ylim = c(0,0.4), xlab = "")
par(new = T)
plot(density(df10), main = "df's with same noncentral parmeter", xlim = c(0,12), ylim = c(0,0.4), xlab = "", col = "blue")
par(new = T)
plot(density(df20), main = "df's with same noncentral parmeter", xlim = c(0,12), ylim = c(0,0.4), xlab = "", col = "skyblue")
par(new = T)
plot(density(df30), main = "df's with same noncentral parmeter", xlim = c(0,12), ylim = c(0,0.4), xlab = "", col = "darkgreen")
par(new = T)
plot(density(df50), main = "df's with same noncentral parmeter", xlim = c(0,12), ylim = c(0,0.4), xlab = "", col = "purple")
par(new = T)
plot(density(df100), main = "df's with same noncentral parmeter", xlim = c(0,12), ylim = c(0,0.4), xlab = "", col = "red")
par(new = T)

par(mfrow = c(1,1))
plot(ecdf(df5), main = "df's with same noncentral parmeter", xlim = c(0, 12), ylim = c(0, 1), xlab = "")
par(new = T)
plot(ecdf(df10), main = "df's with same noncentral parmeter", xlim = c(0, 12), ylim = c(0, 1), xlab = "", col = "blue")
par(new = T)
plot(ecdf(df20), main = "df's with same noncentral parmeter", xlim = c(0, 12), ylim = c(0, 1), xlab = "", col = "skyblue")
par(new = T)
plot(ecdf(df30), main = "df's with same noncentral parmeter", xlim = c(0, 12), ylim = c(0, 1), xlab = "", col = "darkgreen")
par(new = T)
plot(ecdf(df50), main = "df's with same noncentral parmeter", xlim = c(0, 12), ylim = c(0, 1), xlab = "", col = "purple")
par(new = T)
plot(ecdf(df100), main = "df's with same noncentral parmeter", xlim = c(0, 12), ylim = c(0, 1), xlab = "", col = "red")


a <- power.t.test(n = 20:50, delta = 0.7, sig.level = 0.05, alternative = "one.sided")
b <- power.t.test(n = 180:250, delta = 0.28, sig.level = 0.05, alternative = "one.sided")


plot(a$power ~ a$n, pch = 16, title = "Power of t-Test", xlab = "sample size n", ylab = "power")
lines(a$power ~ a$n, col = "red")
abline(v = which(a$power > 0.9)[1]+19, col = "orange")
abline(h = a$power[min(which(a$power > 0.9))], col = "skyblue3")

plot(b$power ~ b$n, pch = 16, title = "Power of t-Test", xlab = "sample size n", ylab = "power")
lines(b$power ~ b$n, col = "red")
abline(v = which(b$power > 0.9)[1]+179, col = "orange")
abline(h = b$power[min(which(b$power > 0.9))], col = "skyblue3")
